server:
  port: 42031

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_spring?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://6.tcp.vip.cpolar.cn:12719/learnspring?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 11111111
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations: classpath:/dao/*.xml
  configuration:
    # 下划线自动转驼峰
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.macro.mall: debug